### ISSUE TITLE
run without installing into current environment

### ISSUE THREAD

**Issue by flip111** [blue-yonder/pyscaffold#100]
The skeleton.py file does not make clear how to just run the file. Since it starts with a shebang i tried the obvious

```
chmod +x skeleton.py
./skeleton.py
```

but then i get
```
» ./skeleton.py
Traceback (most recent call last):
  File "./skeleton.py", line 24, in <module>
    from switches import __version__
ImportError: No module named switches
```
(i called my project `switches`)

this happens with python 3.5.2

I'm totally new to python, so this is really a beginner experience with this tool

**Comment by FlorianWilhelm** [comment]
Hi @flip111 , 

if you check the docstring of `skeleton.py` it should read:
```
This is a skeleton file that can serve as a starting point for a Python
console script. To run this script uncomment the following line in the
entry_points section in setup.cfg:
    console_scripts =
     fibonacci = ${package}.skeleton:run
Then run `python setup.py install` which will install the command `fibonacci`
inside your current environment.
Besides console scripts, the header (i.e. until _logger...) of this file can
also be used as template for Python modules.
Note: This skeleton file can be safely removed if not needed!
```
 Do these instructions help you?

**Comment by flip111** [comment]
No because

```
Then run `python setup.py install` which will install the command `fibonacci`
inside your current environment.
```

and i don't want to install commands on my system just to run this python script

**Comment by FlorianWilhelm** [comment]
Are you using virtual environments `virtualenv` or conda environments btw? If you are not familiar with them you should take a look into them since they allow you to set up little isolated environments to test things like this. But take this only as a side node.

There is actually no point in running `skeleton.py` directly and you are right, I should remove the shebang :-) Will do that in the next version.

**Comment by FlorianWilhelm** [comment]
Well, sorry, this was a too hasty answer. Since `skeleton.py` includes
```
if __name__ == "__main__":
    run()
``` 
this would allow people to not set a console command (by not uncomment the line in setup.cfg) but still allowing them to try this mechanism AFTER having installed it. 
Therefore what you could do, do NOT uncomment the lines 
```
    console_scripts =
     fibonacci = ${package}.skeleton:run
```
just leave them as they are und run `python setup.py install`. Then you can call the skeleton file and it will work.

**Comment by flip111** [comment]
I don't get the point of this install. Why do i need the extra step? What is being installed? What does it give me? Where are the files installed? Can i also uninstall?

I'm just new to python and as far as i know i can run `python hello_world.py` and it works. The readme doesn't say anything about stuff being installed. I liked the look of pyscaffold so that i get a lot of stuff setup already and i don't have to figure out a lot of nifty stuff. But i thought i could just run it out of the box, but now i need to go into configs and comment/uncomment stuff and run installer scripts ?!

Can you make it so that i just `putup project` and then run hello world script ? (in this case `skeleton.py` looks like the hello world script)

**Comment by FlorianWilhelm** [comment]
@flip111 I am not 100% sure you are getting the purpose of this package. It helps Python developers of applications and libraries to easily package them in order to further distribute them. That is actually the opposite of having a Python file somewhere and executing it with `python hello_world.py`. You surely know the command `pip install ...`, right? In order to generate a package of your Python application that can be installed with the help of `pip install` you would use PyScaffold. I guess you have a completely different use-case in your mind. What do you actually want to accomplish and what did you google for to find PyScaffold?

**Comment by flip111** [comment]
I was looking for stuff on how to start a new python project. I just want to get going with the right tooling set up. Similar things i found

https://coderwall.com/p/lt2kew/python-creating-your-project-structure
https://learnpythonthehardway.org/book/ex46.html
https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application
https://jeffknupp.com/blog/2014/02/04/starting-a-python-project-the-right-way/
http://docs.python-guide.org/en/latest/writing/structure/

This library is for distribution only? From reading the readme i thought that was an optional step.

**Comment by FlorianWilhelm** [comment]
Okay, then you are spot on, PyScaffold is the tool for you. Still you might first dig into some other parts of a Python developer's toolchain like conda environments, requirement files, pip and other things. Installing something into a virtual environment, that can be disposed and rebuilt in less then a minute is gonna be your daily job. Running `python setup.py install` or `python setup.py develop` is really normal and even as a developer you are not gonna care where your files go since `pip` will handle it or in the worst case you set up your virtual environment again with `conda` or `virtualenv`.

**Comment by flip111** [comment]
Ok i figured out virtualenv now. Could this possibly be added to a python script to do

```
putup project_name
cd project_name
virtualenv venv
source venv/bin/activate
python setup.py install
python project_name/skeleton.py 1
```

or shall i put this in a shell script ?

**Comment by FlorianWilhelm** [comment]
PyScaffold does only one thing and one thing right. It is not concerned if you are using virtualenv, conda environements or any environments at all, therefore functionality like this won't be included directly. You can put it in a shell script of course but I don't see much advantage of it actually.

Since your issue seems to be resolved, can we close this ticket then?

**Comment by flip111** [comment]
Yes, thank you for support
