### ISSUE TITLE
Support for cookiecutter is under-documented

### ISSUE THREAD

**Issue by brianthelion** [blue-yonder/pyscaffold#102]
First, pyscaffold is great! Thanks!

Second, cookiecutter support is a great addition. Without it, there's no way to do organization-, project-, or framework-specific boilerplate reduction.

As of right now, though, the `putup --with-cookiecutter` experience is a little bit confusing. The extent of the `putup --help` is:
```
PyScaffold is a tool for easily putting up the scaffold of a Python project.

positional arguments:
  PROJECT               project name

optional arguments:
...
  --with-cookiecutter TEMPLATE
                        additionally apply a cookiecutter template
```
The narrative documentation in the [README.md](url) is:
```
Django & Cookiecutter
=====================

Create a `Django project <https://www.djangoproject.com/>`_ with the flag
``--with-django`` which is equivalent to
``django-admin.py startproject my_project`` enhanced by PyScaffold's features.

With the help of `Cookiecutter <https://cookiecutter.readthedocs.org/>`_ it
is possible to customize your project setup. Just use the flag
``--with-cookiecutter TEMPLATE`` to use a cookiecutter template which will be
refined by PyScaffold afterwards.
```
For the naive user, there is (A) a tendency to want to believe that the `--with-cookiecutter` option can be applied to *any existing* cookiecutter template when, in fact, (B) the template needs to be designed to work with pyscaffold. Unintended consequences are par for the course.

To combat #A, there should probably be a warning in both the README and the `--help`.

To combat #B, there should be some narrative documentation that explains how to build a cookiecutter template for pyscaffold.

**Comment by FlorianWilhelm** [comment]
Thanks for your input @brianthelion. I totally agree. The story of the cookiecutter feature is actually that it was requested by a former colleague, implemented and I don't know if ever really used. It is actually quite simple, PyScaffold calls cookiecutter with all parameters (author name, e-mail, package name etc.) and later does its actual job. I haven't myself used this feature so far in practice. Maybe someone from Blue Yonder can comment on that. 
Are you using this feature? It would be great if you could contribute the missing documentation.

**Comment by brianthelion** [comment]
@FlorianWilhelm I would like to use the feature, but will need to author new templates to accomplish what I need to as in #B above. That reduces the overall utility of pyscaffold for me, as there are already cookiecutter templates that do what I want and won't require modification. This sets up an "pyscaffold vs cookiecutter" scenario that I am guessing plenty of other folks are dealing with as well.

**Comment by FlorianWilhelm** [comment]
@brianthelion What is your use-case and which cookiecutter template would you use for it? I am just trying to understand. I often get asked why one would use PyScaffold vs. cookiecutter. Cookiecutter is much more flexible and you have a framework to define your own custom template. PyScaffold on the other hand tries to work just out of the box for 95% of all use-cases. Do you know of any cookiecutter template that does the integration of setuptools_scm, sphinx, pbr, etc. as well as PyScaffold? 
What happens btw, if you just use the cookiecutter template with PyScaffold? Are some files created in wrong directories?

**Comment by brianthelion** [comment]
@FlorianWilhelm No, there are no cookiecutter templates that work as well as pyscaffold *for the basics.* The problem is that as soon as you go beyond the basics you need something that uses customizable templates a-la cookiecutter. The combination of the two would be ideal.

One of the big issues that cookiecutter suffers from is poor support for namespace packages. (This is actually what brought me to pyscaffold in the first place.) So when I tried to `putup --with-namespace= --with-cookiecutter=` I got nonsense. Basically, the result was two completely different directory structures under the current working directory.

The specific things that I would like to do with pyscaffold+cookiecutter are:
- Add organization-specific license language at the top of each .py file.
- Stub out some boilerplate code in the __main__.py of each project.
- Prepopulate the requirements.txt with some things that we'll be using, standard.

**Comment by FlorianWilhelm** [comment]
@brianthelion I think your three points will be hard to accomplish right now since PyScaffold first calls Cookiecutter and let it do its work only then applies its own structure. In case of `requirements.txt` it would overwrite whatever you have done with the help of a Cookiecutter template. So that would need to be changed. I actually know no PyScaffold user that is using the Cookiecutter feature so it would be great if we can make it more useful. 
We could first discuss how to solve your problems conceptually and then if would be great if you could provide a PR. I am always looking for new contributors to it.

**Comment by FlorianWilhelm** [comment]
Thanks to the great work of @abravalheri, this issue is addressed in the current `v3.x` branch that will be released as version 3 when everything is in place.

**Comment by Toekan** [comment]
Hi,

I'm trying to combine cookiecutters with pyscaffold to create a fixed template to create data science projects. In summary, I want to add some folders and files in the source folder and populate the requirements.txt file. Unfortunately the latter is still overwritten by pyscaffold, even though the documentation says the opposite. 

I run

```
putup mypkg --cookiecutter /path/to/project_template
```

In the project_template folder I have:

- cookiecutter.json
- {{cookiecutter.project_name}}
     - src (with more structure inside that is handled correctly by pyscaffold)
     - requirements.txt

What am I doing wrongly that makes pyscaffold overwrite/ignore my requirements.txt file?

Thanks!

**Comment by abravalheri** [comment]
Hi @Toekan, sorry for the inaccurate docs. The logic behind the update of files  is very complex, so I might had conflicting thoughts at the time I was working in this piece of documentation...

The way PyScaffold currently works with Cookiecutter is basically running cookiecutter and then converting the folder into a PyScaffold project with something similar to `putup --force existing_project`. Since we are using the `--force` option, all the conflicting files will be overwritten.

I can try to make it work as described (sorry again by the misleading information) by changing it to use the `--update` flag, but I don't know the implications in terms of behavior and if it will break something.

My main concern at the moment is that, if a `setup.cfg` is created by the cookiecutter, PyScaffold will not generate a new one and then everything will be broken. Of course, I had no idea of how likely (or relevant) is this situation, so I would like to ask @FlorianWilhelm about his thoughts...

I believe we can choose between the following alternatives:

1.  Change the cookiecutter extension to use `--update` instead of `--force` and warn the user if an `setup.cfg` is found.
2. Keep using the `--force` by default, but check first if the user is using the `--update` flag with the cookiecutter.
3. Change the docs to be consistent with the execution and warn the user that everything will be overwritten :(

Meanwhile @Toekan, I think you can use the mental model of `putup --force existing_project` to understand the current limitations of PyScaffold. Additionally you can consider implementing an extension (not so easy, but more powerful)...

Kind regards

**Comment by Toekan** [comment]
Hi,

Thanks for the quick response :). Pyscaffold has really profoundly impacted how I use python, so also thanks for all the effort for this package!

I was reading into extension a bit, but I couldn't fully understand where I should put my extension code. Should I clone pyscaffold and put my extension in the extension folder? Or is there a way to use your extension with pyscaffold without having to put it inside the pyscaffold folder?

**Comment by abravalheri** [comment]
Hi @Toekan, thank you very much!

Your extensions can live in a new and completely separated project/package...

As long as you register the correct setuptools entrypoints and install your new package using pip, everything should be fine.

So let's say you create a package named `pyscaffoldext-mypkg`, using `putput pyscaffoldext-mypkg -p mypkg --namespace pyscaffoldext`. When you are finishing coding, you do `pip install pyscaffoldext-mypkg` and automatically the next time you run `putup -h` you should see new options regarding the usage of your extension.

I will make an effort to go review the documentation trying to remove eventual inconsistencies.
Please feel free to ask us for more information.

**Comment by Toekan** [comment]
Great, thanks for that explanation!

I'll discuss with the others if we just use a cookiecutters template with cookiecutters directly or write an extension for pyscaffold. I think our usecase lays somewhere in between. :)

**Comment by abravalheri** [comment]
@FlorianWilhelm, I have created a proof-of-concept of using `--update` instead of `--force` for cookiecutter templates in the branch [fix-cookiecutter](https://github.com/abravalheri/pyscaffold/tree/fix-cookiecutter) in my fork of PyScaffold... It seems to be working, but I don't know if there are any other philosophical consequences I have not foreseen...

So you might consider having a look, then I can provide it as a PR.

@Toekan, maybe you would like to test it for your project as well, and check if it solves the issue you have previously described.

**Comment by Toekan** [comment]
Hi,

Thanks for all the help!

I've installed your forked version, the fix-cookiecutter branch, but it doesn't seem to work, even without any cookiecutter, just putup pkg_name. It gives the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/Envs/cookie/lib/python3.5/site-packages/pyscaffold/templates/gitignore.template'
```

Also, the installed pyscaffold is 2.5, rather than 3 in the main branch of the unforked version. Maybe that's the reason?

**Comment by abravalheri** [comment]
Sorry @Toekan, could you please use the `fix-cookiecutter` branch before installing?

Assuming you have directly clone my fork, it should be something more or less like the following:
```
git clone https://github.com/abravalheri/pyscaffold
cd pyscaffold
git checkout -b fix-cookiecutter origin/fix-cookiecutter
# you should consider creating and activating a virtualenv here
python setup.py egg_info --egg-base .
python setup.py develop
```
Does it work after that?

**Comment by Toekan** [comment]
Hi, 

Initially I tried to install the correct branch with:
```
pip install git+https://github.com/abravalheri/pyscaffold.git@fix-cookiecutter
```
Which managed to install your fork, but apparently the @fix-cookiecutter. Sorry for that!

After correctly installing the fix-cookiecutter branch (thanks for the help!), the error is gone. I ran:

```
putup my_pkg --cookiecutter /path/to/cookie/template/
```

The package was created, my requirements.txt wasn't overwritten anymore (hurray :) ), but the folder isn't a git repositery. Any idea why?

Again, thanks for all the help! I really think being able to combine pyscaffold with cookiecutter can be very convenient.

**Comment by abravalheri** [comment]
Ok, I found it :sweat_smile:

Basically this is the side effect of using the `--update` flag instead of the `--force`...

The current implemented logic don't run `git init` during an update.

I would have to check with @FlorianWilhelm if I could touch this, since I don't know the reasoning behind this decision.

**Comment by FlorianWilhelm** [comment]
Hi @Toekan, this looks like an interesting problem and thanks @abravalheri for already having fixed some of issues in our documentation about extensions.

It is exactly like @abravalheri explained, first cookie-cutter is run and afterwards PyScaffold does its magic. The reason for this was to keep things simple. If PyScaffold was to be run first, it would be possible that a cookie-cutter template destroys something and you end up with a broken project setup. So with PyScaffold as the last element of the chain and **forcing** all its actions we can almost be sure that you end up with a working project setup even if your cookie-cutter template does something nasty or unexpected. This gives the explanation why we choose `--force` instead of `--update`. We could change that but I am a little bit afraid that this would get us lots of new issues of people reporting strange bugs when using `--cookiecutter` that are actually caused by the behavior of the cookiecutter template and not PyScaffold itself. 
BTW, the reason that `--update` calls no `git init` is that during an normal update of a project's scaffold the repository is already initialized so there is no need. 

There are several possibilities to go on from here:

1.  You use a PyScaffold extension instead of a cookie-cutter template.
2. We totally drop the creation of a `requirements.txt` since it is no longer read by `setup.py` in PyScaffold 3. Also people start to use PipEnv #140 which creates this file automatically. I am still undecided though.
3. We enhance and thus further complicate the cookie-cutter extension to handle this use-case. This would be my least preferred solution but possible.

**Comment by abravalheri** [comment]
Sorry, @FlorianWilhelm, have you merged `fix-cookiecutter` directly from my fork? I am starting to get confused with the amount of branches that I am opening...

But basically yes, the behavior remains the same, the order and sequence that things are done, changes a little bit...

**Comment by FlorianWilhelm** [comment]
@abravalheri: I only merged your PRs, so maybe I confused it. You can make your local branch into a PR and it should be fine as long as it doesn't break something existing. Let me have a look into the PR then a bit later, I am traveling right now.

**Comment by abravalheri** [comment]
I will close this issue again now, since the documentation has been updated to reflect what happens in practice.

Unfortunately changing the built-in cookiecutter extension to support this use case is incompatible with PyScaffold force/update logic/mental model.

**Comment by FlorianWilhelm** [comment]
@Toekan I created a small example extension under [pyscaffoldext-pyproject](https://github.com/pyscaffold/pyscaffoldext-pyproject). Together with the changes of @abravalheri it should be quite easy for you to do what you want to accomplish. Please let us know if that works for you and sorry for misusing you as our guinea pig for the new extension system ;-)

**Comment by Toekan** [comment]
As I'm for from an expert on packaging, I just took your example, changed the template, changed some names of functions, but it worked! Pyscaffold seems to do everything it is expected and the cookiecutter template is there and the requirements.txt isn't overwritten. :) 

Am I right to think the important part is here: 
```
return self.register(
            actions,
            self.add_requirements,
            after='define_structure')
```
The after='define_structure' makes sure the requirements template is added after the previous empty one was made?

Also, completely out of the scope of this thread: but any advice on how I could point the adding of the requirements template to the template from the cookiecutter repo rather than a new seperate file inside my pyscaffold_extension? Just to avoid maintaining two different versions of this file. :)

**Comment by abravalheri** [comment]
Hi @Toekan, glad to see that you managed to have it from the examples! Good work.

Regarding your first question, it is exactly that bit that do the trick. As long your extension is placed between `define_structure` and `create_structure` you are basically overriding the content of the file that will be written to the disk.

If you want to keep a file that is already in the disk (the cookiecutter extension populates the project dir before `create_structure`), I guess you can just remove the corresponding entry from the `struct` dict. It is worth a try...

**Comment by FlorianWilhelm** [comment]
@abravalheri, I think what @brianthelion means is how he can pass a repo git repo url to the extension he built on command-line so that the extension grabs the file from there and not from within the extension package itself. 

I think passing a parameter like a git url is quite easy, right @abravalheri? But fetching a file from there surely needs a git library. How is cookie-cutter doing this?

**Comment by abravalheri** [comment]
Uumm if receiving an URL from the command line is the issue, an example about how to do that can be found at the cookiecutter example itself (basically create a custom argparse action, or add extra options).

However if he is using the cookiecutter extension anyway, maybe it might be easier to let cookiecutter do the heavy lift, and make PyScaffold just forget about the `requirements.txt` file, as if it was never included by `define_structure`...
