### ISSUE TITLE
Consider dropping PBR

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#116]
Newer versions of setuptools allow configuration with the help of `setup.cfg` for almost all options. A few years ago this was not possible and therefore PBR was used to achieve this. PBR itself is considered by many people as quite a hack and it is really hard to debug sometimes. For version 3.0 of PyScaffold we could consider dropping PBR and replacing it with the standard functionality of more recent versions of setuptools. Checkout the [setuptools' documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) for more details.

**Comment by HolgerPeters** [comment]
PBR was the reason I stopped actively using pyscaffold.

**Comment by abravalheri** [comment]
+1 for sure.
But let me ask you what would be the impact of this change on issue #48?
The idea would be allow the user to directly modify setup.py, or would
PyScaffold stick with the declarative approach using setup.cfg?

Do this change also affects #79?

>

**Comment by FlorianWilhelm** [comment]
Yes, this would fix #48 since Cython usage would be done just as it is meant to be according to setuptools by changing `setup.py` directly. Most other more common configuration would still be done via `setup.cfg` in a declarative way (see [here](http://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)) because it is just way easier and one of the more important reasons people like PyScaffold.
This would also affect #79. Currently, PBR reads in `requirements.txt` to generate to package dependencies. After we switched back to pure setuptools this link would be broken, meaning that one has to configure dependencies in setup.cfg and can define whatever is wanted in `requirements.txt`. I think this is okay since many people want to define dependencies without version pinning for the actual package but with version version pinning in requirements.txt. One could even provide a PyScaffold plugin/extension allowing for a `requirements.in` to be used with `pip-compile` and `pip-sync` as described [here](http://nvie.com/posts/better-package-management/). All these are things I have been asked for but could not include due to the dependency to PBR and the fact that I did not want to trade the declarative `setup.cfg` for another feature. So now with newer versions of setuptools, this is possible. 
Also #98 could be solved by the switch since PBR also handles the call to [`sphinx-apidoc`](http://www.sphinx-doc.org/en/stable/invocation.html#invocation-apidoc) right now which we would then do allowing us to fix this issue but of course this also comes with cost of maintaining this feature.

**Comment by abravalheri** [comment]
It is great that so many issues can be addressed after dropping PBR.

May I just drop a few more questions? (Just trying to understand and checking if I can contribute to something...)

Right now `setup.py` is always replaced whenever the user does a `--update` or `--force`. This is possible because all custom configuration is supposed to live inside `setup.cfg`. But with this change I think we cannot keep this assumption. Therefore, will the user be required to manually update `setup.py`  after each release? Or will the approach be splitting it into 2 files, one managed by PyScaffold and another customized (that is not replaced)?

About `sphinx-apidoc`, is it necessary to keep custom code in order to run `python setup.py docs`? Isn't `make -C docs html` enough?

**Comment by FlorianWilhelm** [comment]
The updating issue is really a good point to bring up. You are right that in this case we should no longer overwrite ``setup.py`` when calling ``--update`` without ``--force``.  Hopefully our vanilla ``setup.py`` does not change at least for minor and patch level updates. Major updates like moving from 2.x to 3.x are really hard to support and I don't know if it is worth the effort, million things could go wrong and giving a short manual to the user how one would do it manually might be better than some automated process.

So far I have never really used ``make -C docs html`` only the direct invocation with ``pyhon setup.py docs`` which is an entry_point registered by Sphinx. If I remember correctly in one of the 1.x versions of PyScaffold I was then executing ``sphinx-apidoc`` within Sphinx's ``conf.py`` in order to generate the proper rst files. It was only a few lines but maybe today there is a better way to do it since Sphinx evolved a lot and I found it always strange that ``sphinx-apidoc`` is kept so separate. I assume ``make -C docs html`` also does not call ``sphinx-apidoc``, right?

**Comment by abravalheri** [comment]
Well, I have changed `sphinx_makefile.template` in order to call `sphinx-apidoc` as a task dependency.
I am not sure if there is a flag for `conf.py` to do that automatically. The only thing I was able to find is a [`autosummary_generate`](http://www.sphinx-doc.org/en/stable/ext/autosummary.html#confval-autosummary_generate) flag, but it uses the [`sphinx.ext.autosummary`](http://www.sphinx-doc.org/en/stable/ext/autosummary.html) extension instead of [`sphinx.ext.autodoc`](http://www.sphinx-doc.org/en/stable/ext/autodoc.html).

**Comment by FlorianWilhelm** [comment]
In the current master branch pbr is dropped.
