### ISSUE TITLE
Check code style etc

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#117]
Use flake8 to check code convention and style in Travis

**Comment by abravalheri** [comment]
The pre-commit hook is configured to already use flake8 in branch v3.x, so
all the new code *should *be fine at least, but more specific style guides
may require a more powerful tool like pylint (that can also be integrated
with pre-commit).

One option to make it available within travis is running the command:

pre-commit run --all-files

The problem with this approach is that maybe old code (prior to v3.x) will
not be compliant and break the builds (and therefore may require a huge
change in the entire code base to make it ok).

Alternatively, pre-commit documentation
<http://pre-commit.com/#usage-in-continuous-integration> suggest that is
possible to check just the code that have changed with a command:

git diff-tree --no-commit-id --name-only -r $REVISION | xargs pre-commit
run --files

I think this is a better approach since it allows the code base to adopt
new conventions incrementally (anytime a person changes a file, per is
responsible to update that file to the new convention).

Of course it is necessary to figure out how to use travis env vars in this
command, differentiating between simple commits and pull-requests (maybe
some scripting with TRAVIS_COMMIT, TRAVIS_PULL_REQUEST_BRANCH,
TRAVIS_PULL_REQUEST_SHA, or just TRAVIS_COMMIT_RANGE).

**Comment by FlorianWilhelm** [comment]
I added `flake8 --count` to the `system_test.sh`.
