### ISSUE TITLE
Rework the setup.cfg with the help of configparser

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/pyscaffold#139]
Using `string.template` for more complicated templates like `setup.cfg` is quite cumbersome and would also not allow to update `setup.cfg` in case of new versions. We should use `configparser` instead to create `setup.cfg` as well as to update it later on.

This can be postponed to version 3.1 since an update from pre 3.0 versions will not be possible anyway.

**Comment by FlorianWilhelm** [comment]
This issue seems to be actually way more complicated than initially thought. After some investigation there seems to be no Python package right now that allows to read, manipulate and write a config file without potentially changing the order of the key/value pairs and dropping all comments of the original config file.

I appreciate any hints on this.

**Comment by abravalheri** [comment]
The order of the key/value pairs seems to be easy to be kept if an OrderedDict is used, however keeping the comments is a little bit trickier...

In order to write comments, PyScaffold would have to use some [hacks](https://stackoverflow.com/questions/6620637/writing-comments-to-files-with-configparser), but storing the comments in a read operation, changing the options and then writing seems pretty much impossible.

In order to do that, PyScaffold would need something that reads the `cfg` file and returns an AST, but I don't think this is somehow easily available.

Are there other alternatives than writing a parser by hand?

**Comment by FlorianWilhelm** [comment]
Maybe the alternative is to check if large parts of Python's internal `configparser` could be used. Using an `OrderedDict` at least keeps the order when reading a config file. No we would just need to include comments somehow and make sure that they also are written back.

**Comment by FlorianWilhelm** [comment]
I am trying to implement the needed functionality in an own project named [ConfigUpdate](https://github.com/pyscaffold/configupdater) that can later be included as `contrib` package. It's making good progress but needs some more time.

**Comment by FlorianWilhelm** [comment]
@abravalheri, I just released a first `0.1` version of [ConfigUpdater](https://github.com/pyscaffold/configupdater). Let me know what you think. 

My next step would be now to include it into PyScaffold and use it to allow updating `setup.cfg` from version 3.0 to version 3.1, i.e. moving `setup_requires` and `options.entry_points` over as well as updating the `pyscaffold` section.

**Comment by FlorianWilhelm** [comment]
Done
