### ISSUE TITLE
clean up imports in __init__.py

### ISSUE THREAD

**Issue by reuvenpo** [blue-yonder/pyscaffold#158]
Currently in the `__init__.py ` file there are two names imported from `setuptools`. These names should probably be `del`ed before the module finishes running to clean up the package's namespace.

For example:

```python
# -*- coding: utf-8 -*-
from pkg_resources import get_distribution, DistributionNotFound

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = 'test-pscf-proj'
    __version__ = get_distribution(dist_name).version
except DistributionNotFound:
    __version__ = 'unknown'
finally:
    del get_distribution, DistributionNotFound
```

This is because if anyone runs `from myproj import *`, they're going to get `get_distribution` and `DistributionNotFound` into their module namespace as well.

By the way, looking at this file, the `dist_name` can probably be replaced with `__name__` which removes the need to explicitly spell it out in the `__init__` file.

Also, is `'unknown'` an appropriate value here? it's not a valid PEP440 version string if i understand correctly. Maybe `None` is more appropriate? I'm not sure what's the right thing to do here but `'unknown'` smells wrong to me.

**Comment by FlorianWilhelm** [comment]
Hi @reuvenpo, I got the point with `finally: del get_distribution, DistributionNotFound`. Thanks. Would you make a small PR for that?

Regarding the usage of `__name__`. This is how it was done before and it doesn't work if your project has a different name compared to the package you are shipping. Common examples are for instance scikit-learn that ships a package sklearn and pytorch that ships a package torch. 
In this case `__name__` would be resolve into the package and `get_distribution` doesn't find the distribution. 

Regarding the `unknown`. I like to have the same data type here, namely string, so that the user doesn't always need to check for `None` when `__version__` is used. Otherwise this could lead to really strange bugs if for some reason (maybe a bug in setuptools or setuptools_scm) the right version is not resolved and the user's code breaks because it doesn't handle `None`. Does this make sense? Do you have a better PEP440 string in mind?

**Comment by reuvenpo** [comment]
I'll make a pull request in a bit.

I got your point on the `__name__`. Didn't really consider that use-case.

As for the version name, if setuptools or setuptools_scm had a bug in it, wouldn't that mean we wouldn't get to this line executing, or alternatively we'll just get a malformed version string, which would silently be assigned to `__version__`.

After briefly looking at PEP440 again, it seems that the "canonical" scheme doesn't really support the idea of an "unknown version" (that's kind of expected really), as you can see in the section on [Public version identifiers](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers), but we can abuse the [Local version identifiers](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) a bit to express this idea.

I think that `0.0.0+unknown` or just `0+unknown` could be a good option. PyPI won't accept a distribution whose version is `unknown`, but it also wouldn't accept a version containing a local version identifier either(not that PyPI cares about ones `__version__` variable). In this sense it reserves the old behavior of assigning an invalid version to the `__version__` variable, while at the same time conforming to the PEP.

**Comment by FlorianWilhelm** [comment]
Having thought about this I think that having an invalid version string is actually a good thing. `unknown` will not be accepted by PyPI so you will not be able to upload something broken. So for me `unknown` as `__version__` is somewhere between an exception that will kill your application and a version string that is PEP440 conform. 

In a nutshell, if you see `unknown` you know something is broken (maybe even inside setuptools_scm) but at least it will not break your current source installation.

**Comment by reuvenpo** [comment]
That's pretty reasonable.
If one sees `'0.0.0+unknown'`, one might think that it was generated by setuptools_scm, so a clean `'unknown'` is better in that regard.

**Comment by FlorianWilhelm** [comment]
@reuvenpo, alright then. I think this issue can be closed now.

**Comment by patricknraanes** [comment]
Hi! Shouldn't ``dist_name`` also be ``del``ed ?

**Comment by abravalheri** [comment]
Hi Patrick, I find `dist_name` quite useful, specially when you are using
`appdirs`. So I am voting for it to stay :)
