### ISSUE TITLE
tox.ini template is slow at running tests

### ISSUE THREAD

**Issue by aspiers** [blue-yonder/pyscaffold#161]
IIUC [`src/pyscaffold/templates/tox_ini.template`](https://github.com/blue-yonder/pyscaffold/blob/master/src/pyscaffold/templates/tox_ini.template) causes tox to do an sdist install even though the tests are unlikely to need it.  This can slow testing down a lot.  If I'm correct, this should be fixed by adding `usedevelop = True` to the `[testenv]` section:

http://tox.readthedocs.io/en/latest/example/general.html#avoiding-expensive-sdist

See also #160.

**Comment by FlorianWilhelm** [comment]
Thanks @aspiers for your suggestion. Surely in large projects the `usedevelop = True` option could help to speed up things but for smaller projects the overhead is quite minimal anyway. The downside to it is that the actual packaging and installing is no longer tested by tox. 

So imagine you have forgotten to add some data file to the repository and thus it won't be in the source distribution. In this case with `usedevelop = True` everything should run smoothely but without it you will see the error that the data file is missing as it should be.

What do you think about a compromise here. We could add the commented line `# usedevelop = True` to the template together with a comment to uncomment it in order to speed up the unit tests if necessary.

**Comment by FlorianWilhelm** [comment]
@abravalheri, I added it to the template as a comment as discussed and made a PR. I think we can close this now.

**Comment by aspiers** [comment]
Sorry for the slow reply.  I didn't personally find that for smaller projects the overhead was minimal - in fact it was a small project of mine which prompted submitting this ticket.  However I think the compromise here is good, so thanks a lot!
