### ISSUE TITLE
Support markdown for readme and setup.py

### ISSUE THREAD

**Issue by patrick-motard** [blue-yonder/pyscaffold#163]
Warehouse now supports markdown per [this PR](https://github.com/pypa/warehouse/issues/869).

An explanation of how to use the feature can be found [here](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi). 

It would be nice to be able to tell pyscaffold to use markdown instead of .rst.

**Comment by FlorianWilhelm** [comment]
Thanks @patrick-motard for this suggestion. I also prefer markdown over rst but it still seems that rst is more prevalent in the Python world. Since the goal of PyScaffold is to drive a standard for package creation I don't think it is a good idea to support markdown and rst with the help of a command-line flag. First of all it makes things much more complicated and defies the idea of a standard. So maybe in a new major version update we should completely switch to markdown not only in the Readme but also in Sphinx to keep it consistent. Do you have any idea how many Python projects are moving to markdown? I am definitely interested in a discussion about this.

As a short term solution for you, you could easily write a PyScaffold extension for this.

**Comment by FlorianWilhelm** [comment]
I started working on an extension https://github.com/pyscaffold/pyscaffoldext-markdown

**Comment by FlorianWilhelm** [comment]
A first release of the [markdown extension](https://github.com/pyscaffold/pyscaffoldext-markdown) was just published on [PyPI](https://pypi.org/project/pyscaffoldext-markdown/). 
@patrick-motard please check it out and let us know what you think.

I'll close this ticket for now. Please report further issues in the issue tracker of the extension.
