### ISSUE TITLE
Use python git bindings instead of parsing git subprocess output 

### ISSUE THREAD

**Issue by kopf** [blue-yonder/pyscaffold#42]
Creating an issue here, as I think it should probably be discussed, and I didn't want to derail the discussion on #40 (sorry @xhochy !)

@FlorianWilhelm - in https://github.com/blue-yonder/pyscaffold/pull/40#issuecomment-86002562 you say that you're against the idea of using python bindings such as `pygit2` as it would "lead to further restrictions on the user". Can you explain what you mean by "further restrictions"? 

My impression is that we want to keep the requirements for `pyscaffold` as lean as possible. Introducing a dependency on `pygit2` would mean the user would have to install it, and (possibly) also already have a system package such as `git-lib` installed, or something similar. 

With all things considered, is that not preferable to the current situation? By "current situation", I mean:

* Parsing output from git, which is bound to break sooner or later, and which makes backwards compatibility (with regards to git) extremely difficult, due to differing output or behaviour between versions
* `pyscaffold` possibly breaking for those who use git in a language other than English
* Rube Goldberg-style solutions to problems (e.g. checking output from `git rev-parse` to determine whether we're inside a git repo)

**Comment by FlorianWilhelm** [comment]
Point taken and from a developer's perspective I totally agree. Why do we reinvent the wheel if there are libraries like libgit2 and pygit2? But it comes with a price tag. We would have additional dependencies that are quite uncommon. The library pygit2 is of version 0.22.0 and has about 4700 monthly downloads on pypi which is not much. The Ubuntu package of libgit2 (https://launchpad.net/ubuntu/+source/libgit2) states Trusty Tahr (14.04) as being the first Ubuntu version to include it. That's less than one year ago. Windows users would have to actually compile libgit2 before using PyScaffold? I'm all for using libraries but libgit2 and pygit2 seem to be rather bleeding-edge and don't even have post-1.0 releases.
Maybe there are other ways to work around the problems you state:
* We should avoid parsing output wherever possible and should not assume English as the user's language. This is why we solve PR #40 without parsing git's error messages.
* Unittests that check if PyScaffold works properly in non-English should be provided.
* Rube Goldberg machines or let's just call them hacks are sometimes the pragmatic way to go. We should just make sure that they are isolated so that they can be easily replaced later on when libgit2/pygit2 are more mature and established. This is why we have all those small functions like `is_git_installed`, `is_git_configured`, `is_git_repo` etc.

I'd like to here some more comments on that. Anyone else wants to share his/her opinion?

**Comment by sebastianneubauer** [comment]
I have a tendency to agree with @FlorianWilhelm . I also do not like hacks or works-on-my-machine solutions. But even worse are avoidable dependencies. We should think of circuit breakers, so that the worst thing that could happen is, that the git repository is not initiated correctly but all the rest is working.
To the dependency-hell:
I would love to see more packages in the unix style of thinking: Do ONE thing, and do it well!
And I add: and do it with as few dependencies as possible.
I don't know these git packages, but my experience is often an awfull feature creep in some packages like these. If all we want to do is to initialize a git repo and maybe get the latest tag, we should consider to just do that in our own codebase and maybe even with a dirty hack...If what we want to do is to write a github clone, we should consider using a "almighty" library...but we are not (yet)

**Comment by kopf** [comment]
OK, this has been open for about 2 weeks now, and there doesn't seem to be too much discussion. This was really more of a "Denkanstoß" than anything else - I wanted, primarily, to find out why pyscaffold was doing things this way as opposed to the other way.

As both @sebastianneubauer and @FlorianWilhelm are opposed to the idea, I'll close this issue, and propose we should re-open it and discuss things here if at some time in the future the current approach begins to cause us problems.
