### ISSUE TITLE
Cannot build or install project with git submodule

### ISSUE THREAD

**Issue by willu47** [blue-yonder/pyscaffold#92]
When `git submodule` is used to create a sub-repository within a repo, `python setup.py install sdist bdist` fail with the error: 
    `error: can't copy 'exactVerify/shipquant': doesn't exist or not a regular file`

**Comment by FlorianWilhelm** [comment]
This is most likely a bug in PBR as pointed out in the [PBR bugtracker](https://bugs.launchpad.net/pbr/+bug/1530867). When it is fixed in PBR I will update the version PyScaffold uses. My recommendation is to use ``git subtree`` anyway. You can check out how I use it in PyScaffold for PBR and setuptools-scm.

**Comment by FlorianWilhelm** [comment]
@willu47 The problem still exists in version 2.5.6 since the authors of PBR seem to ignore this issue right now. Another workaround is to use either ``python setup.py develop`` or ``python setup.py sdist``  followed by ``pip install dist/your_package.tar.gz``. It seems only ``python setup.py install`` is choking on the submodule directory.

**Comment by willu47** [comment]
Okay, thanks for the update.  We've found a workaround for now.

**Comment by FlorianWilhelm** [comment]
Since PBR will be dropped with version 3 of PyScaffold, this bug is no longer present in the current master branch.
